services:
    app:
        build: 
          args: 
              user: 'lucas-borges'
              uid: 1000 
          dockerfile: Dockerfile 
        container_name: app
        extra_hosts:
          - "host.docker.internal:host-gateway"
        environment:
          - DB_HOST=db
          - DB_DATABASE=laravel
          - DB_USERNAME=root
          - DB_PASSWORD=root
        volumes:
          - .:/var/www
        networks:
          - app-network-01
        depends_on:
          - db
          - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
        networks:
          - app-network-01
        depends_on:
          - app
    
    queue:
        build: 
            args: 
                user: 'lucas-borges'
                uid: 1000
            dockerfile: Dockerfile
        container_name: queue    
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes: 
            - .:/var/www
        depends_on: 
            - redis
        networks: 
            - app-network-01

    db:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
          - "33006:3306"
        volumes:
          - ./.docker/dbdata:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=laravel
          - MYSQL_ROOT_PASSWORD=root
        networks:
          - app-network-01

    redis:
        image: redis:latest
        networks: 
            - app-network-01

networks:
    app-network-01:
        driver: bridge